name: Integration Tests

on: [pull_request]

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        backend: ['', '--archive-backend posix']
        tests: ['integration', 'security', 'robustness']
        python-version: [3.6]
        exclude:
          # excludes node 4 on macOS
          - backend: ''
            tests: 'security'
          - backend: ''
            tests: 'robustness'
    
    runs-on: ${{ matrix.os }}
    
    name: |
      ${{ matrix.tests }} tests with backend option '${{ matrix.backend }}'
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install bats
      run: |
        git clone https://github.com/bats-core/bats-core.git
        pushd bats-core && git checkout v1.1.0 && sudo ./install.sh /usr/local && popd
    - name: Bootstrap requirements
      run: |
        pip install git+https://github.com/EGA-archive/crypt4gh.git@v1.0
        pip install pika==1.0.1
        pip install shyaml
        sudo apt-get install expect
    - name: Build image
      run:  |
        docker build -f Dockerfile \
                     --build-arg LEGA_GID=1000 \
                     --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
                     --build-arg SOURCE_COMMIT=$(git rev-parse --short HEAD) \
                     --tag nbisweden/ega-base:latest \
                     .
    - name: Bootstrap with backend '${{ matrix.backend }}' and Start Services
      run: |
        pushd deploy
        pip install bcrypt
        make bootstrap ARGS="${{ matrix.backend }}"
        sudo chown 70 private/config/certs/db.ca.key
        make up
        docker-compose ps
        sleep 80
        popd
    - name: Run ${{ matrix.tests }} test
      run: |
        bats tests/${{ matrix.tests }}
